### ISSUE TITLE
Missing information to run atmospi it from the browser

### ISSUE THREAD

**Issue by aukeboskma** [mstenta/atmospi#11]
I installed atmospi automaticly through puppet what worked great by the way. But I don't know how to see the logs and graphs in the browser. Can you please tell me how to get that working? 

Thanks
Auke

**Comment by janvdbeek** [comment]
Hi all,
I installed atmospi via puppet and later, when I couldn't get it to work, I installed it manually but still no luck. I get the atmospi webpage but there are no measurement data. When I manually execute measure-ds18b20.py I get the following error message:

Traceback (most recent call last):
File "/home/pi/atmospi/Atmospi/measure-ds18b20.py", line 75, in <module>
id = db.fetchone () [0]
TypeError: 'NoneType' object has no attribute '__ getitem __'

I've read this issue and tried a lot of things but i'm stuck. So I think i need some help :-)

Thanks in advance.

**Comment by mstenta** [comment]
Hey @janvdbeek! You may have found a new bug... that code was changed recently, and maybe it isn't properly detecting new devices.

We should create a new issue to debug it...

In the meantime, I think you can get it to work by manually adding your sensors to the Devices table. You will need to find out the unique address of the sensor you have. Do you know how to do that?

Once you have that address, insert it into the Devices table with the following SQL:

    INSERT INTO Devices (DeviceID, Type, SerialID, Label) VALUES(NULL, 'ds18b20', '1234567890', 'Name');

Change "1234567890" to the actual sensor ID, and change "Name" to the name you want to give it.

**Comment by mstenta** [comment]
I created a new issue here: #27
