### ISSUE TITLE
DHT22 sensor 

### ISSUE THREAD

**Issue by aukeboskma** [mstenta/atmospi#15]
Hi,

I'm trying to add a DHT22 sensor. But I got an error and I have no idea how to fix this. Hope you can help.

pi@raspberrypi ~/atmospi/Atmospi $ sudo ./measure-dht.py
Traceback (most recent call last):
  File "./measure-dht.py", line 52, in <module>
    readings = read_sensors()
  File "./measure-dht.py", line 33, in read_sensors
    tc, h = dhtreader.read(sensor_types[device['type']], device['pin'])
TypeError: 'NoneType' object is not iterable

Settings.py looks like this
# Atmospi settings.
settings = {

    # Absolute path to the SQLite database file.
    'db': '/home/pi/atmospi/log.db',

    # Define the DHT devices and the GPIO pin they are connected to.
        'dht_devices': {
                'Humidity1': {
                        'type': 'DHT22',
                        'pin': 29
                }
        }
}

**Comment by mstenta** [comment]
Closing this issue, because you got it working! :-)
