### ISSUE TITLE
Variable precision

### ISSUE THREAD

**Issue by mstenta** [mstenta/atmospi#17]
Add a setting for the precision to use when recording sensor readings. Currently, the readings are a lot more precise than they need to be, and that essentially just means unnecessary storage space in the database.

Perhaps we can default the precision to 2, but allow it to be changed in settings.py.

**Comment by ot3** [comment]
I'm not sure what a precision of 2 is but one decimal after the period would seem like a useful default.

**Comment by mstenta** [comment]
By "2" I mean 2 decimal points... so 50.15 degrees, for example. One is probably sufficient for most uses, so I figured I'd just take it one step further. :-)

**Comment by mstenta** [comment]
This is done!

Release notes: https://github.com/mstenta/atmospi/releases/tag/v0.2.2
