### ISSUE TITLE
Beaglebone issues

### ISSUE THREAD

**Issue by amorsent** [mstenta/atmospi#2]
In the measurement script, I had to comment out the following two lines to avoid errors.

os.system('modprobe w1-gpio')
os.system('modprobe w1-therm')

The Beaglebone uses the Angstrom distro rather than Raspian, and it has a different way of managing hardware.

I managed to get my W1 bus running using the following tutorial:
http://hipstercircuits.com/dallas-one-wire-temperature-reading-on-beaglebone-black-with-dto/

The script works if I comment out those lines, but I get errors otherwise.

**Comment by mstenta** [comment]
I'm going to close this for now. If anyone is interested in making Atmospi work on Beaglebone, feel free to reopen and contribute!
