### ISSUE TITLE
Axis title does not show preferred unit of measure

### ISSUE THREAD

**Issue by ot3** [mstenta/atmospi#26]
In v0.2.3 the axis title always shows degrees Fahrenheit and does not get the preferred UoM from default_settings.py

**Comment by mstenta** [comment]
Do you mean in v0.2.3? Because that's the version that added temperature units to default_settings.py. Before that it was always Fahrenheit.

**Comment by ot3** [comment]
Corrected; my bad :-)

**Comment by mstenta** [comment]
Oh ok hmm... maybe I just missed one of the replacements? I'll take a quick look...

**Comment by mstenta** [comment]
Ah ha! Found it... line 76 of Atmospi/static/atmospi.js should be:

text: 'Temperature (°' + settings['t_unit'] + ')'

I will push a fix...

**Comment by mstenta** [comment]
Fixed in the master branch!

**Comment by ot3** [comment]
Works! Thanks!
