### ISSUE TITLE
Sensor not recognized; increased delay in measure-ds18b20.py to 0.5s

### ISSUE THREAD

**Issue by ot3** [mstenta/atmospi#28]
I added another ds18b20 which now has a total of 9 sensors, with the latest addition having a 11m long cable. I noticed that random sensors dropped out and were not recognized by the system. After increasing the delay time in line39 from 0.2 to 0.5 seconds, the problem disappeared [at least for now]

line 39            time.sleep(0.2) --> time.sleep(0.5)

**Comment by mstenta** [comment]
Sounds good to me!

Would you mind putting it together into a pull request? Or I'll try to remember to commit it next time I'm working on it.

**Comment by ot3** [comment]
Michael,

Will do as soon as I figure out how to do this. I'll need to do some
research.

Best regards, Alfred

**Comment by mstenta** [comment]
Sounds good! It's a great thing to learn, and not very difficult once you get it. Plus it will mean you can more easily contribute to this project and others!

Here's a great reference: https://help.github.com/articles/fork-a-repo/

You can actually do it all within Github itself, I think. Fork the repo, then edit the file and make a change, commit it, and then create a pull request. I'll get a notification, and be able to click a single button to pull your change in.

**Comment by mstenta** [comment]
Oh. You did this! Closed.
