### ISSUE TITLE
Setting for default temperature unit (F/C)

### ISSUE THREAD

**Issue by mstenta** [mstenta/atmospi#5]
Currently only shows Fahrenheit. Add a setting that allows displaying values in Celcius too.

**Comment by ot3** [comment]
I need to display degrees Celsius but couldn't figure out from the info provided how to hard code this change [assuming there's no provision in settings.py yet]. Can you please provide a few more hints?

**Comment by aukeboskma** [comment]
Just change all the code as mentioned in message: https://github.com/mstenta/atmospi/issues/5#issuecomment-58440367 

So https://github.com/mstenta/atmospi/blob/master/Atmospi/data.py#L15
Change 
        fields = 'Timestamp, F'
to 
        fields = 'Timestamp, C'

https://github.com/mstenta/atmospi/blob/master/Atmospi/__init__.py#L77
Change
    rows = db.select('SELECT MAX(Timestamp), Device, F FROM Temperature GROUP BY Device');
to
    rows = db.select('SELECT MAX(Timestamp), Device, C FROM Temperature GROUP BY Device');

After that reboot you Pi. 

Now you should see the Celsius data but the graph is still in F. But I hope this gives you a starting point :)

**Comment by mstenta** [comment]
I should really just get around to making a patch for this... so you can change it via a setting in settings.py :-)

Glad to see another person using it! Welcome @ot3!

**Comment by ot3** [comment]
Many thanks for your efforts. Works like a charm so far! If you get around to addressing the temperature unit via settings.py [timeframe?] you may also want to consider the following enhancements:
1. variable precision, i.e. rounding the temperature to e.g. the nearest 0.1 degree
2. a calibration offset table in which you can specify the delta-T for each sensor compared to a calibrated thermometer. 

None of the above are essential but would be nice enhancements.

P.S. I'm going to use atmospi to debug/setup a poorly designed radiant floor heating system.

**Comment by mstenta** [comment]
@ot3: Those are great ideas! In fact, I was already considering adding a rounding factor, because right now there is a lot more precision than is necessary.  So maybe I will default it to a precision of 2 decimal places, but allow others to change it in their settings.py.

I also really like your idea of a calibration offset.

I created two new feature requests:

#17
#18

**Comment by mstenta** [comment]
Not sure what the timeframe on this would be... patches are welcome if you have the time/ability!

**Comment by ot3** [comment]
Michael,

Time yes, ability very limited as my UNIX knowledge is from the early 80's.
I'm already very pleased I could get it to run without too many problems :-)

**Comment by ot3** [comment]
I succeeded in hard coding the following changes:
1. temperature in degrees Celsius
2. 1 digit precision [e.g. 21.2]

Thanks to both of you for helping me getting started.

**Comment by mstenta** [comment]
@ot3: Great! Can you post how you did the 1 digit precision in #17? So we have somewhere to start, or if someone else sees it they can make a patch.

**Comment by ot3** [comment]
Change measure-ds18b20.py by applying the round function.

Original:  temp_c = float(temp_string) / 1000.0
Modified: temp_c = round(float(temp_string) / 1000.0,1)

**Comment by mstenta** [comment]
I am working on implementing this permanently in the temperature_unit branch: https://github.com/mstenta/atmospi/tree/temperature_unit

**Comment by mstenta** [comment]
This is done!

Release notes with upgrade instructions: https://github.com/mstenta/atmospi/releases/tag/v0.2.3
